version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT= 3002
      - DATABASE_URL=
      - JWT_SECRET=
      - JWT_REFRESH=
      - MAIL_USER=
      - MAIL_PASSWORD=
      - URL_CLIENT=
    restart: always
